version: "3.9"
services:
  postgres:
    container_name: database
    build: ./postgres/
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data
  back_end:
    container_name: back_end
    build: ./back-end-fhome
    expose:
      - 3001
    volumes:
      - ./page:/back_end/usr/src/app
    links:
      - database
  front_end:
    container_name: front_end
    build: ./front-end-fhome
    expose:
      - 3000
    volumes:
      - ./page:/front_end/usr/src/app
  nginx:
    container_name: nginx
    build: ./nginx/
    expose:
      - 80
    links:
      - front_end
      - back_end
      - nginx-proxy
      - letsencrypt
    environment: 
      - VIRTUAL_HOST=egam.online
      - LETSENCRYPT_HOST=egam.online
    restart: always
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
volumes:
  database:
  certs:
  html:
  vhostd:
